import 'package:flutter/material.dart';
import 'package:flutterapp/iimunapp/generatediimuntvfiresidewidget/generated/GeneratedVideo1Widget3.dart';
import 'package:flutterapp/iimunapp/generatediimuntvfiresidewidget/generated/GeneratedHeaderWidget4.dart';
import 'package:flutterapp/iimunapp/generatediimuntvfiresidewidget/generated/GeneratedVideo2Widget2.dart';
import 'package:flutterapp/iimunapp/generatediimuntvfiresidewidget/generated/GeneratedVideo4Widget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/iimunapp/generatediimuntvfiresidewidget/generated/GeneratedVideo3Widget1.dart';
import 'package:flutterapp/iimunapp/generatediimuntvfiresidewidget/generated/GeneratedVideo5Widget1.dart';
import 'package:flutterapp/iimunapp/generatediimuntvfiresidewidget/generated/GeneratedVideo6Widget1.dart';
import 'package:flutterapp/iimunapp/generatediimuntvfiresidewidget/generated/GeneratedVideo7Widget1.dart';
import 'package:flutterapp/iimunapp/generatediimuntvfiresidewidget/generated/GeneratedVideo8Widget1.dart';
import 'package:flutterapp/iimunapp/generatediimuntvfiresidewidget/generated/GeneratedNavFIRESIDEWidget.dart';
import 'package:flutterapp/iimunapp/generatediimuntvfiresidewidget/generated/GeneratedVideo9Widget1.dart';

/* Frame IIMUNTV-FIRESIDE
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIIMUNTVFIRESIDEWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 2294.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 414.0,
                            height: 896.0,
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.zero,
                                    child: Container(
                                      color: Color.fromARGB(255, 255, 255, 255),
                                    ),
                                  ),
                                  Positioned(
                                    left: 35.0,
                                    top: 2134.0,
                                    right: 39.0,
                                    bottom: null,
                                    width: null,
                                    height: 160.0,
                                    child: GeneratedVideo9Widget1(),
                                  ),
                                  Positioned(
                                    left: 35.0,
                                    top: 1889.0,
                                    right: 39.0,
                                    bottom: null,
                                    width: null,
                                    height: 160.0,
                                    child: GeneratedVideo8Widget1(),
                                  ),
                                  Positioned(
                                    left: 35.0,
                                    top: 1644.0,
                                    right: 39.0,
                                    bottom: null,
                                    width: null,
                                    height: 160.0,
                                    child: GeneratedVideo7Widget1(),
                                  ),
                                  Positioned(
                                    left: 36.0,
                                    top: 1399.0,
                                    right: 38.0,
                                    bottom: null,
                                    width: null,
                                    height: 160.0,
                                    child: GeneratedVideo6Widget1(),
                                  ),
                                  Positioned(
                                    left: 36.0,
                                    top: 1154.0,
                                    right: 38.0,
                                    bottom: null,
                                    width: null,
                                    height: 160.0,
                                    child: GeneratedVideo5Widget1(),
                                  ),
                                  Positioned(
                                    left: 36.0,
                                    top: 909.0,
                                    right: 38.0,
                                    bottom: null,
                                    width: null,
                                    height: 160.0,
                                    child: GeneratedVideo4Widget1(),
                                  ),
                                  Positioned(
                                    left: 37.0,
                                    top: 664.0,
                                    right: 37.0,
                                    bottom: null,
                                    width: null,
                                    height: 160.0,
                                    child: GeneratedVideo3Widget1(),
                                  ),
                                  Positioned(
                                    left: 37.0,
                                    top: 419.0,
                                    right: 37.0,
                                    bottom: null,
                                    width: null,
                                    height: 160.0,
                                    child: GeneratedVideo2Widget2(),
                                  ),
                                  Positioned(
                                    left: 37.0,
                                    top: 174.0,
                                    right: 37.0,
                                    bottom: null,
                                    width: null,
                                    height: 160.0,
                                    child: GeneratedVideo1Widget3(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 45.0,
                                    right: 0.0,
                                    bottom: null,
                                    width: null,
                                    height: 60.0,
                                    child: GeneratedHeaderWidget4(),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: null,
              top: null,
              right: null,
              bottom: 0.0,
              width: 414.0,
              height: 54.0,
              child: TransformHelper.translate(
                  x: -1.00, y: 0.00, z: 0, child: GeneratedNavFIRESIDEWidget()),
            )
          ]),
    ));
  }
}
