import 'package:flutter/material.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos2widget/generated/GeneratedEp18Widget1.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos2widget/generated/GeneratedEp10Widget1.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos2widget/generated/GeneratedEp13Widget1.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos2widget/generated/GeneratedEp16Widget1.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos2widget/generated/GeneratedEp6Widget1.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos2widget/generated/GeneratedSpecialWidget.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos2widget/generated/GeneratedEp17Widget1.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos2widget/generated/GeneratedHeaderWidget17.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos2widget/generated/GeneratedEp1Widget1.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos2widget/generated/GeneratedEp5Widget1.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos2widget/generated/GeneratedEp8Widget1.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos2widget/generated/GeneratedBackWidget3.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos2widget/generated/GeneratedEp3Widget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos2widget/generated/GeneratedEp9Widget1.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos2widget/generated/GeneratedEp12Widget1.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos2widget/generated/GeneratedEp2Widget1.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos2widget/generated/GeneratedEp7Widget1.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos2widget/generated/GeneratedEp11Widget1.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos2widget/generated/GeneratedEp14Widget1.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos2widget/generated/GeneratedEp4Widget1.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos2widget/generated/GeneratedEp15Widget1.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos2widget/generated/GeneratedEp19Widget1.dart';

/* Frame KTK-Videos-2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedKTKVideos2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Container(
            height: 5698.0,
            child: Stack(children: [
              Container(
                  width: constraints.maxWidth,
                  child: Container(
                    width: 414.0,
                    height: 896.0,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        overflow: Overflow.visible,
                        children: [
                          ClipRRect(
                            borderRadius: BorderRadius.zero,
                            child: Container(
                              color: Color.fromARGB(255, 255, 255, 255),
                            ),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 45.0,
                            right: 0.0,
                            bottom: null,
                            width: null,
                            height: 60.0,
                            child: GeneratedHeaderWidget17(),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 115.0,
                            right: null,
                            bottom: null,
                            width: 414.0,
                            height: 60.0,
                            child: GeneratedBackWidget3(),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.821256038647343;

                              final double height =
                                  constraints.maxHeight * 0.21344866071428573;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.0893719806763285,
                                    y: constraints.maxHeight *
                                        0.29129464285714285,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedEp1Widget1(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.821256038647343;

                              final double height =
                                  constraints.maxHeight * 0.21344866071428573;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.0893719806763285,
                                    y: constraints.maxHeight *
                                        0.5993303571428571,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedEp2Widget1(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.821256038647343;

                              final double height =
                                  constraints.maxHeight * 0.21344866071428573;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.0893719806763285,
                                    y: constraints.maxHeight *
                                        0.9084821428571429,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedEp3Widget1(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.821256038647343;

                              final double height =
                                  constraints.maxHeight * 0.21344866071428573;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.0893719806763285,
                                    y: constraints.maxHeight *
                                        1.2165178571428572,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedEp4Widget1(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.821256038647343;

                              final double height =
                                  constraints.maxHeight * 0.21344866071428573;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.0893719806763285,
                                    y: constraints.maxHeight *
                                        1.5256696428571428,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedEp5Widget1(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.821256038647343;

                              final double height =
                                  constraints.maxHeight * 0.21344866071428573;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.0893719806763285,
                                    y: constraints.maxHeight *
                                        1.8325892857142858,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedEp6Widget1(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.821256038647343;

                              final double height =
                                  constraints.maxHeight * 0.21344866071428573;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.0893719806763285,
                                    y: constraints.maxHeight * 2.140625,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedEp7Widget1(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.821256038647343;

                              final double height =
                                  constraints.maxHeight * 0.21344866071428573;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.0893719806763285,
                                    y: constraints.maxHeight *
                                        2.4486607142857144,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedEp8Widget1(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.821256038647343;

                              final double height =
                                  constraints.maxHeight * 0.21344866071428573;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.0893719806763285,
                                    y: constraints.maxHeight *
                                        2.7566964285714284,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedEp9Widget1(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.821256038647343;

                              final double height =
                                  constraints.maxHeight * 0.21344866071428573;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.0893719806763285,
                                    y: constraints.maxHeight *
                                        3.064732142857143,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedEp10Widget1(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.821256038647343;

                              final double height =
                                  constraints.maxHeight * 0.21344866071428573;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.0893719806763285,
                                    y: constraints.maxHeight *
                                        3.372767857142857,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedEp11Widget1(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.821256038647343;

                              final double height =
                                  constraints.maxHeight * 0.21344866071428573;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.0893719806763285,
                                    y: constraints.maxHeight *
                                        3.6808035714285716,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedEp12Widget1(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.821256038647343;

                              final double height =
                                  constraints.maxHeight * 0.21344866071428573;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.0893719806763285,
                                    y: constraints.maxHeight *
                                        3.9888392857142856,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedEp13Widget1(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.821256038647343;

                              final double height =
                                  constraints.maxHeight * 0.21344866071428573;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.0893719806763285,
                                    y: constraints.maxHeight * 4.296875,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedEp14Widget1(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.821256038647343;

                              final double height =
                                  constraints.maxHeight * 0.21344866071428573;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.0893719806763285,
                                    y: constraints.maxHeight *
                                        4.604910714285714,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedEp15Widget1(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.821256038647343;

                              final double height =
                                  constraints.maxHeight * 0.21344866071428573;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.0893719806763285,
                                    y: constraints.maxHeight *
                                        4.913225446428571,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedEp16Widget1(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.821256038647343;

                              final double height =
                                  constraints.maxHeight * 0.21344866071428573;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.0893719806763285,
                                    y: constraints.maxHeight *
                                        5.220982142857143,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedEp17Widget1(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.821256038647343;

                              final double height =
                                  constraints.maxHeight * 0.21344866071428573;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.0893719806763285,
                                    y: constraints.maxHeight * 5.529296875,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedEp18Widget1(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.821256038647343;

                              final double height =
                                  constraints.maxHeight * 0.21344866071428573;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.0893719806763285,
                                    y: constraints.maxHeight *
                                        5.837611607142857,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedEp19Widget1(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.821256038647343;

                              final double height =
                                  constraints.maxHeight * 0.21344866071428573;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.0893719806763285,
                                    y: constraints.maxHeight *
                                        6.145926339285714,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedSpecialWidget(),
                                    ))
                              ]);
                            }),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
