import 'package:flutter/material.dart';
import 'package:flutterapp/iimunapp/generatedexperientiallearningwidget/generated/GeneratedHeaderWidget12.dart';
import 'package:flutterapp/iimunapp/generatedexperientiallearningwidget/generated/GeneratedWiththedawnofthe21stcenturyitisquintessentialtohaveprac.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/iimunapp/generatedexperientiallearningwidget/generated/GeneratedIIMUNspecializesincateringtostudentsacrosstheglobeAllpr.dart';
import 'package:flutterapp/iimunapp/generatedexperientiallearningwidget/generated/GeneratedWhatisExperientialLearningWidget.dart';
import 'package:flutterapp/iimunapp/generatedexperientiallearningwidget/generated/GeneratedWhybecomeaglobetrotterwithIIMUNWidget.dart';

/* Frame ExperientialLearning
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedExperientialLearningWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 3361.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 414.0,
                      height: 896.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 2.2737367544323206e-13,
                              top: 45.0,
                              right: -2.2737367544323206e-13,
                              bottom: null,
                              width: null,
                              height: 60.0,
                              child: GeneratedHeaderWidget12(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 1.0048309178743962;

                                final double height =
                                    constraints.maxHeight * 0.25223214285714285;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: 0,
                                      y: constraints.maxHeight * 0.1171875,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedWhatisExperientialLearningWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.9444444444444444;

                                final double height =
                                    constraints.maxHeight * 1.7991071428571428;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.03140096618357488,
                                      y: constraints.maxHeight * 0.3671875,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedWiththedawnofthe21stcenturyitisquintessentialtohaveprac(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.9444444444444444;

                                final double height =
                                    constraints.maxHeight * 1.3058035714285714;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.021739130434782608,
                                      y: constraints.maxHeight * 2.4453125,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedIIMUNspecializesincateringtostudentsacrosstheglobeAllpr(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 1.0048309178743962;

                                final double height =
                                    constraints.maxHeight * 0.25223214285714285;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: 0,
                                      y: constraints.maxHeight * 2.1796875,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedWhybecomeaglobetrotterwithIIMUNWidget(),
                                      ))
                                ]);
                              }),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
