import 'package:flutter/material.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos3widget/generated/GeneratedEp4Widget2.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos3widget/generated/GeneratedEp2Widget2.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos3widget/generated/GeneratedHeaderWidget18.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos3widget/generated/GeneratedEp1Widget2.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos3widget/generated/GeneratedEp8Widget2.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos3widget/generated/GeneratedEp6Widget2.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos3widget/generated/GeneratedEp5Widget2.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos3widget/generated/GeneratedEp10Widget2.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos3widget/generated/GeneratedEp11Widget2.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos3widget/generated/GeneratedEp3Widget2.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos3widget/generated/GeneratedEp9Widget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos3widget/generated/GeneratedEp7Widget2.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos3widget/generated/GeneratedBackWidget4.dart';

/* Frame KTK-Videos-3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedKTKVideos3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Container(
            height: 3215.25,
            child: Stack(children: [
              Container(
                  width: constraints.maxWidth,
                  child: Container(
                    width: 414.0,
                    height: 896.0,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        overflow: Overflow.visible,
                        children: [
                          ClipRRect(
                            borderRadius: BorderRadius.zero,
                            child: Container(
                              color: Color.fromARGB(255, 255, 255, 255),
                            ),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 45.0,
                            right: 0.0,
                            bottom: null,
                            width: null,
                            height: 60.0,
                            child: GeneratedHeaderWidget18(),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 115.0,
                            right: null,
                            bottom: null,
                            width: 414.0,
                            height: 60.0,
                            child: GeneratedBackWidget4(),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.821256038647343;

                              final double height =
                                  constraints.maxHeight * 0.21344866071428573;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.0893719806763285,
                                    y: constraints.maxHeight *
                                        0.29129464285714285,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedEp1Widget2(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.821256038647343;

                              final double height =
                                  constraints.maxHeight * 0.21344866071428573;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.0893719806763285,
                                    y: constraints.maxHeight * 0.599609375,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedEp2Widget2(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.821256038647343;

                              final double height =
                                  constraints.maxHeight * 0.21344866071428573;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.0893719806763285,
                                    y: constraints.maxHeight *
                                        0.9079241071428571,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedEp3Widget2(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.821256038647343;

                              final double height =
                                  constraints.maxHeight * 0.21344866071428573;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.0893719806763285,
                                    y: constraints.maxHeight *
                                        1.2165178571428572,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedEp4Widget2(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.821256038647343;

                              final double height =
                                  constraints.maxHeight * 0.21344866071428573;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.0893719806763285,
                                    y: constraints.maxHeight *
                                        1.5248325892857142,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedEp5Widget2(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.821256038647343;

                              final double height =
                                  constraints.maxHeight * 0.21344866071428573;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.0893719806763285,
                                    y: constraints.maxHeight *
                                        1.8331473214285714,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedEp6Widget2(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.821256038647343;

                              final double height =
                                  constraints.maxHeight * 0.21344866071428573;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.0893719806763285,
                                    y: constraints.maxHeight *
                                        2.1417410714285716,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedEp7Widget2(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.821256038647343;

                              final double height =
                                  constraints.maxHeight * 0.21344866071428573;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.0893719806763285,
                                    y: constraints.maxHeight *
                                        2.4500558035714284,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedEp8Widget2(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.821256038647343;

                              final double height =
                                  constraints.maxHeight * 0.21344866071428573;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.0893719806763285,
                                    y: constraints.maxHeight *
                                        2.7583705357142856,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedEp9Widget2(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.821256038647343;

                              final double height =
                                  constraints.maxHeight * 0.21344866071428573;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.0893719806763285,
                                    y: constraints.maxHeight *
                                        3.066685267857143,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedEp10Widget2(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.821256038647343;

                              final double height =
                                  constraints.maxHeight * 0.21344866071428573;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.0893719806763285,
                                    y: constraints.maxHeight * 3.375,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedEp11Widget2(),
                                    ))
                              ]);
                            }),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
