import 'package:flutter/material.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos1widget/generated/GeneratedEp15Widget.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos1widget/generated/GeneratedEp9Widget.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos1widget/generated/GeneratedEp19Widget.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos1widget/generated/GeneratedEp14Widget.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos1widget/generated/GeneratedEp7Widget.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos1widget/generated/GeneratedEp1Widget.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos1widget/generated/GeneratedBackWidget2.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos1widget/generated/GeneratedHeaderWidget16.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos1widget/generated/GeneratedEp5Widget.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos1widget/generated/GeneratedEp13Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos1widget/generated/GeneratedEp12Widget.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos1widget/generated/GeneratedEp17Widget.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos1widget/generated/GeneratedEp21Widget.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos1widget/generated/GeneratedEp16Widget.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos1widget/generated/GeneratedEp20Widget.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos1widget/generated/GeneratedEp10Widget.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos1widget/generated/GeneratedEp4Widget.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos1widget/generated/GeneratedEp11Widget.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos1widget/generated/GeneratedEp6Widget.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos1widget/generated/GeneratedEp3Widget.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos1widget/generated/GeneratedEp18Widget.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos1widget/generated/GeneratedEp2Widget.dart';
import 'package:flutterapp/iimunapp/generatedktkvideos1widget/generated/GeneratedEp8Widget.dart';

/* Frame KTK-Videos-1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedKTKVideos1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Container(
            height: 5977.0,
            child: Stack(children: [
              Container(
                  width: constraints.maxWidth,
                  child: Container(
                    width: 414.0,
                    height: 896.0,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        overflow: Overflow.visible,
                        children: [
                          ClipRRect(
                            borderRadius: BorderRadius.zero,
                            child: Container(
                              color: Color.fromARGB(255, 255, 255, 255),
                            ),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 45.0,
                            right: 0.0,
                            bottom: null,
                            width: null,
                            height: 60.0,
                            child: GeneratedHeaderWidget16(),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 115.0,
                            right: null,
                            bottom: null,
                            width: 414.0,
                            height: 60.0,
                            child: GeneratedBackWidget2(),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.821256038647343;

                              final double height =
                                  constraints.maxHeight * 0.21344866071428573;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.0893719806763285,
                                    y: constraints.maxHeight *
                                        0.29129464285714285,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedEp1Widget(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.821256038647343;

                              final double height =
                                  constraints.maxHeight * 0.21344866071428573;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.0893719806763285,
                                    y: constraints.maxHeight * 0.599609375,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedEp2Widget(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.821256038647343;

                              final double height =
                                  constraints.maxHeight * 0.21344866071428573;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.0893719806763285,
                                    y: constraints.maxHeight *
                                        0.9079241071428571,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedEp3Widget(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.821256038647343;

                              final double height =
                                  constraints.maxHeight * 0.21344866071428573;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.0893719806763285,
                                    y: constraints.maxHeight *
                                        1.2162388392857142,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedEp4Widget(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.821256038647343;

                              final double height =
                                  constraints.maxHeight * 0.21344866071428573;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.0893719806763285,
                                    y: constraints.maxHeight *
                                        1.5245535714285714,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedEp5Widget(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.821256038647343;

                              final double height =
                                  constraints.maxHeight * 0.21344866071428573;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.0893719806763285,
                                    y: constraints.maxHeight *
                                        1.8325892857142858,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedEp6Widget(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.821256038647343;

                              final double height =
                                  constraints.maxHeight * 0.21344866071428573;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.0893719806763285,
                                    y: constraints.maxHeight * 2.140625,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedEp7Widget(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.821256038647343;

                              final double height =
                                  constraints.maxHeight * 0.21344866071428573;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.0893719806763285,
                                    y: constraints.maxHeight *
                                        2.4486607142857144,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedEp8Widget(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.821256038647343;

                              final double height =
                                  constraints.maxHeight * 0.21344866071428573;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.0893719806763285,
                                    y: constraints.maxHeight *
                                        2.7569754464285716,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedEp9Widget(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.821256038647343;

                              final double height =
                                  constraints.maxHeight * 0.21344866071428573;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.0893719806763285,
                                    y: constraints.maxHeight *
                                        3.0652901785714284,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedEp10Widget(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.821256038647343;

                              final double height =
                                  constraints.maxHeight * 0.21344866071428573;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.0893719806763285,
                                    y: constraints.maxHeight *
                                        3.3738839285714284,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedEp11Widget(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.821256038647343;

                              final double height =
                                  constraints.maxHeight * 0.21344866071428573;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.0893719806763285,
                                    y: constraints.maxHeight *
                                        3.6821986607142856,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedEp12Widget(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.821256038647343;

                              final double height =
                                  constraints.maxHeight * 0.21344866071428573;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.0893719806763285,
                                    y: constraints.maxHeight *
                                        3.990513392857143,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedEp13Widget(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.821256038647343;

                              final double height =
                                  constraints.maxHeight * 0.21344866071428573;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.0893719806763285,
                                    y: constraints.maxHeight *
                                        4.299107142857143,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedEp14Widget(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.821256038647343;

                              final double height =
                                  constraints.maxHeight * 0.21344866071428573;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.0893719806763285,
                                    y: constraints.maxHeight * 4.607421875,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedEp15Widget(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.821256038647343;

                              final double height =
                                  constraints.maxHeight * 0.21344866071428573;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.0893719806763285,
                                    y: constraints.maxHeight *
                                        4.915736607142857,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedEp16Widget(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.821256038647343;

                              final double height =
                                  constraints.maxHeight * 0.21344866071428573;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.0893719806763285,
                                    y: constraints.maxHeight *
                                        5.224051339285714,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedEp17Widget(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.821256038647343;

                              final double height =
                                  constraints.maxHeight * 0.21344866071428573;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.0893719806763285,
                                    y: constraints.maxHeight *
                                        5.532366071428571,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedEp18Widget(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.821256038647343;

                              final double height =
                                  constraints.maxHeight * 0.21344866071428573;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.0893719806763285,
                                    y: constraints.maxHeight *
                                        5.840680803571429,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedEp19Widget(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.821256038647343;

                              final double height =
                                  constraints.maxHeight * 0.21344866071428573;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.0893719806763285,
                                    y: constraints.maxHeight *
                                        6.148995535714286,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedEp20Widget(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.821256038647343;

                              final double height =
                                  constraints.maxHeight * 0.21344866071428573;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.0893719806763285,
                                    y: constraints.maxHeight *
                                        6.457310267857143,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedEp21Widget(),
                                    ))
                              ]);
                            }),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
