import 'package:flutter/material.dart';
import 'package:flutterapp/iimunapp/generatedoneworldmainpagewidget/generated/GeneratedHeaderWidget14.dart';
import 'package:flutterapp/iimunapp/generatedoneworldmainpagewidget/generated/GeneratedOneWorldJune1Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/iimunapp/generatedoneworldmainpagewidget/generated/GeneratedFrame2Widget5.dart';

/* Frame OneWorld-MainPage
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOneWorldMainPageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height =
                      constraints.maxHeight * 0.10379464285714286;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: constraints.maxHeight * 0.18303571428571427,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFrame2Widget5(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 45.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 60.0,
                child: GeneratedHeaderWidget14(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.36231884057971014;

                  final double height =
                      constraints.maxHeight * 0.23446878365107945;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.3188405797101449,
                        y: constraints.maxHeight * 0.39285714285714285,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedOneWorldJune1Widget(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
