import 'package:flutter/material.dart';
import 'package:flutterapp/iimunapp/generatedrishabhsirwordswidget/generated/GeneratedXWidget.dart';
import 'package:flutterapp/iimunapp/generatedrishabhsirwordswidget/generated/GeneratedAsItakeamomenttocelebrateoverthe9yearsgonebyIamhumbledi.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame RishabhSirWords
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRishabhSirWordsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1383.000259399414,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 414.0,
                      height: 896.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 122, 135, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.9275358633142738;

                                final double height =
                                    constraints.maxHeight * 1.4229913439069475;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.0386473890663921,
                                      y: constraints.maxHeight *
                                          0.12053573131561279,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedAsItakeamomenttocelebrateoverthe9yearsgonebyIamhumbledi(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.09420289855072464;

                                final double height =
                                    constraints.maxHeight * 0.05915176442691258;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.8792272742819671,
                                      y: constraints.maxHeight *
                                          0.05022321002823966,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedXWidget(),
                                      ))
                                ]);
                              }),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
