import 'package:flutter/material.dart';
import 'package:flutterapp/iimunapp/generatedmaindropdownwidget/generated/GeneratedEVENTSWidget.dart';
import 'package:flutterapp/iimunapp/generatedmaindropdownwidget/generated/GeneratedMONTHLYWidget.dart';
import 'package:flutterapp/iimunapp/generatedmaindropdownwidget/generated/GeneratedFAQWidget.dart';
import 'package:flutterapp/iimunapp/generatedmaindropdownwidget/generated/GeneratedHOMEWidget.dart';
import 'package:flutterapp/iimunapp/generatedmaindropdownwidget/generated/GeneratedABOUTWidget.dart';
import 'package:flutterapp/iimunapp/generatedmaindropdownwidget/generated/GeneratedIIMUNTVWidget.dart';
import 'package:flutterapp/iimunapp/generatedmaindropdownwidget/generated/GeneratedCONTACTWidget.dart';

/* Frame Main-DropDown
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMainDropDownWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 276.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 276.0,
                height: 70.0,
                child: GeneratedHOMEWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 70.0,
                right: null,
                bottom: null,
                width: 276.0,
                height: 70.0,
                child: GeneratedABOUTWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 140.0,
                right: null,
                bottom: null,
                width: 276.0,
                height: 70.0,
                child: GeneratedIIMUNTVWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 210.0,
                right: null,
                bottom: null,
                width: 276.0,
                height: 117.0,
                child: GeneratedEVENTSWidget(),
              ),
              Positioned(
                left: 4.547473508864641e-13,
                top: 327.0,
                right: null,
                bottom: null,
                width: 276.0,
                height: 70.0,
                child: GeneratedMONTHLYWidget(),
              ),
              Positioned(
                left: 4.547473508864641e-13,
                top: 397.0,
                right: null,
                bottom: null,
                width: 276.0,
                height: 70.0,
                child: GeneratedCONTACTWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 467.0,
                right: null,
                bottom: null,
                width: 276.0,
                height: 70.0,
                child: GeneratedFAQWidget(),
              )
            ]),
      ),
    ));
  }
}
