import 'package:flutter/material.dart';
import 'package:flutterapp/iimunapp/generatedmun360widget1/generated/GeneratedMUN360inyourschoolWidget.dart';
import 'package:flutterapp/iimunapp/generatedmun360widget1/generated/GeneratedAniimuninitiativeWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/iimunapp/generatedmun360widget1/generated/GeneratedDearFacultyMemberDoyouwanttoorganiseavirtualinterschool.dart';
import 'package:flutterapp/iimunapp/generatedmun360widget1/generated/GeneratedHeaderWidget13.dart';

/* Frame MUN360
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMUN360Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 3083.000213623047,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 414.0,
                      height: 896.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 1.0048309178743962;

                                final double height =
                                    constraints.maxHeight * 0.1361607313156128;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: 0,
                                      y: constraints.maxHeight *
                                          0.14620535714285715,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedMUN360inyourschoolWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 1.0048309178743962;

                                final double height =
                                    constraints.maxHeight * 0.05580360548836844;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: 0,
                                      y: constraints.maxHeight *
                                          0.31473214285714285,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedAniimuninitiativeWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.9444443707304876;

                                final double height =
                                    constraints.maxHeight * 3.0379467010498047;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.03140097079069718,
                                      y: constraints.maxHeight *
                                          0.4029017516544887,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedDearFacultyMemberDoyouwanttoorganiseavirtualinterschool(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 45.0,
                              right: 0.0,
                              bottom: null,
                              width: null,
                              height: 60.0,
                              child: GeneratedHeaderWidget13(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
