import 'package:flutter/material.dart';
import 'package:flutterapp/iimunapp/generatedknowmorechampionshipwidget/generated/GeneratedContactWidget.dart';
import 'package:flutterapp/iimunapp/generatedknowmorechampionshipwidget/generated/GeneratedContactWidget2.dart';
import 'package:flutterapp/iimunapp/generatedknowmorechampionshipwidget/generated/GeneratedDigitalFlagshipConference580Widget.dart';
import 'package:flutterapp/iimunapp/generatedknowmorechampionshipwidget/generated/GeneratedBasicDetailsWidget1.dart';
import 'package:flutterapp/iimunapp/generatedknowmorechampionshipwidget/generated/GeneratedFrame12Widget.dart';
import 'package:flutterapp/iimunapp/generatedknowmorechampionshipwidget/generated/GeneratedFlagship32Widget.dart';
import 'package:flutterapp/iimunapp/generatedknowmorechampionshipwidget/generated/GeneratedHeaderWidget11.dart';
import 'package:flutterapp/iimunapp/generatedknowmorechampionshipwidget/generated/GeneratedFrame11Widget.dart';
import 'package:flutterapp/iimunapp/generatedknowmorechampionshipwidget/generated/GeneratedDescriptionWidget2.dart';
import 'package:flutterapp/iimunapp/generatedknowmorechampionshipwidget/generated/GeneratedBackWidget1.dart';
import 'package:flutterapp/iimunapp/generatedknowmorechampionshipwidget/generated/GeneratedRectangle16Widget1.dart';
import 'package:flutterapp/iimunapp/generatedknowmorechampionshipwidget/generated/GeneratedItenaryWidget2.dart';
import 'package:flutterapp/iimunapp/generatedknowmorechampionshipwidget/generated/GeneratedCommitteesAgendasWidget1.dart';
import 'package:flutterapp/iimunapp/generatedknowmorechampionshipwidget/generated/GeneratedInclusionsWidget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame KnowMore - Championship
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedKnowMoreChampionshipWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 6177.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 414.0,
                      height: 896.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width = constraints.maxWidth;

                                final double height =
                                    constraints.maxHeight * 0.34821455819266184;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: 0,
                                      y: constraints.maxHeight *
                                          1.1685265132359095,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedDescriptionWidget2(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 1513.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 1214.0,
                              child: GeneratedCommitteesAgendasWidget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 1.002415458937198;

                                final double height =
                                    constraints.maxHeight * 0.13616071428571427;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: 0,
                                      y: constraints.maxHeight *
                                          0.6674107142857143,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedDigitalFlagshipConference580Widget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width = constraints.maxWidth;

                                final double height =
                                    constraints.maxHeight * 0.2901786395481655;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: 0,
                                      y: constraints.maxHeight * 0.8515625,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedBasicDetailsWidget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.9975845410628019;

                                final double height =
                                    constraints.maxHeight * 0.06696428571428571;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: 0,
                                      y: constraints.maxHeight *
                                          0.12834821428571427,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedBackWidget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 2.2737367544323206e-13,
                              top: 45.0,
                              right: -2.2737367544323206e-13,
                              bottom: null,
                              width: null,
                              height: 60.0,
                              child: GeneratedHeaderWidget11(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 210.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 331.9683532714844,
                              child: GeneratedFlagship32Widget(),
                            ),
                            Positioned(
                              left: 128.0,
                              top: 5942.0,
                              right: null,
                              bottom: null,
                              width: 158.0,
                              height: 51.51123046875,
                              child: GeneratedFrame11Widget(),
                            ),
                            Positioned(
                              left: 128.0,
                              top: 6038.0,
                              right: null,
                              bottom: null,
                              width: 158.0,
                              height: 51.5107421875,
                              child: GeneratedFrame12Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 1.0048309178743962;

                                final double height =
                                    constraints.maxHeight * 0.04799107142857143;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: 0,
                                      y: constraints.maxHeight *
                                          6.845982142857143,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedRectangle16Widget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 5767.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 144.0,
                              child: GeneratedContactWidget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 2881.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 246.0,
                              child: GeneratedInclusionsWidget2(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.9999999262860432;

                                final double height =
                                    constraints.maxHeight * 1.410714830671038;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: 0,
                                      y: constraints.maxHeight *
                                          3.661830357142857,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedItenaryWidget2(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.9999999262860432;

                                final double height =
                                    constraints.maxHeight * 0.125;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: 0,
                                      y: constraints.maxHeight *
                                          6.183035714285714,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedContactWidget2(),
                                      ))
                                ]);
                              }),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
