import 'package:flutter/material.dart';
import 'package:flutterapp/iimunapp/generatedyouthhutwidget/generated/GeneratedAnEducationalSoireeWidget.dart';
import 'package:flutterapp/iimunapp/generatedyouthhutwidget/generated/GeneratedWedontknowaboutyoubutwesureashellaretiredwiththesameZoo.dart';
import 'package:flutterapp/iimunapp/generatedyouthhutwidget/generated/GeneratedPlayisthehighestformofresearchAlbertEinsteinWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/iimunapp/generatedyouthhutwidget/generated/GeneratedYOUTHHUTWidget3.dart';
import 'package:flutterapp/iimunapp/generatedyouthhutwidget/generated/GeneratedHeaderWidget5.dart';

/* Frame YouthHut
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedYouthHutWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 2011.999755859375,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 414.0,
                      height: 896.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 1.0048309178743962;

                                final double height =
                                    constraints.maxHeight * 0.09598214285714286;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: 0,
                                      y: constraints.maxHeight *
                                          0.1707587582724435,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedYOUTHHUTWidget3(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 2.2737367544323206e-13,
                              top: 45.0,
                              right: -2.2737367544323206e-13,
                              bottom: null,
                              width: null,
                              height: 60.0,
                              child: GeneratedHeaderWidget5(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.9516908212560387;

                                final double height =
                                    constraints.maxHeight * 0.13616068022591726;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.02657012432669672,
                                      y: constraints.maxHeight *
                                          0.26450889451163156,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedAnEducationalSoireeWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 1.0048309178743962;

                                final double height =
                                    constraints.maxHeight * 0.23995535714285715;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: 0,
                                      y: constraints.maxHeight * 0.3984375,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedPlayisthehighestformofresearchAlbertEinsteinWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.9444444444444444;

                                final double height =
                                    constraints.maxHeight * 1.609374727521624;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.03140091089810726,
                                      y: constraints.maxHeight *
                                          0.6361607142857143,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedWedontknowaboutyoubutwesureashellaretiredwiththesameZoo(),
                                      ))
                                ]);
                              }),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
