import 'package:flutter/material.dart';
import 'package:flutterapp/iimunapp/generatedaboutwidget/generated/GeneratedWhatDoWeDoWidget.dart';
import 'package:flutterapp/iimunapp/generatedaboutwidget/generated/GeneratedAboutAboutWidget.dart';
import 'package:flutterapp/iimunapp/generatedaboutwidget/generated/GeneratedDividerLineWidget.dart';
import 'package:flutterapp/iimunapp/generatedaboutwidget/generated/GeneratedPresidentsAddressWidget.dart';
import 'package:flutterapp/iimunapp/generatedaboutwidget/generated/GeneratedHeaderWidget1.dart';
import 'package:flutterapp/iimunapp/generatedaboutwidget/generated/GeneratedFrame2Widget.dart';
import 'package:flutterapp/iimunapp/generatedaboutwidget/generated/GeneratedImage1Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/iimunapp/generatedaboutwidget/generated/GeneratedMillenialsneedtobeempoweredtobedoersRishabhShahFounderP.dart';
import 'package:flutterapp/iimunapp/generatedaboutwidget/generated/GeneratedDividerLineWidget1.dart';
import 'package:flutterapp/iimunapp/generatedaboutwidget/generated/GeneratedDividerLineWidget2.dart';
import 'package:flutterapp/iimunapp/generatedaboutwidget/generated/GeneratedFrame13Widget.dart';

/* Frame About
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAboutWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Container(
            height: 3203.000114440918,
            child: Stack(children: [
              Container(
                  width: constraints.maxWidth,
                  child: Container(
                    width: 414.0,
                    height: 896.0,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        overflow: Overflow.visible,
                        children: [
                          ClipRRect(
                            borderRadius: BorderRadius.zero,
                            child: Container(
                              color: Color.fromARGB(255, 255, 255, 255),
                            ),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 860.0,
                            right: 0.0,
                            bottom: null,
                            width: null,
                            height: 2.0,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width = constraints.maxWidth - 66.0;
                              final double scaleX =
                                  width <= 0 ? 0 : (width / 348.0);

                              final Widget child = GeneratedDividerLineWidget();
                              return Stack(children: [
                                Transform(
                                  transform: Matrix4(
                                      scaleX,
                                      0,
                                      0,
                                      0,
                                      0,
                                      1,
                                      0,
                                      0,
                                      0,
                                      0,
                                      1,
                                      0,
                                      33.0 * scaleX,
                                      860.0,
                                      0,
                                      1),
                                  alignment: Alignment.topLeft,
                                  child: SizedBox.expand(child: child),
                                )
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 2652.0,
                            right: 0.0,
                            bottom: null,
                            width: null,
                            height: 2.0,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width = constraints.maxWidth - 66.0;
                              final double scaleX =
                                  width <= 0 ? 0 : (width / 348.0);

                              final Widget child =
                                  GeneratedDividerLineWidget1();
                              return Stack(children: [
                                Transform(
                                  transform: Matrix4(
                                      scaleX,
                                      0,
                                      0,
                                      0,
                                      0,
                                      1,
                                      0,
                                      0,
                                      0,
                                      0,
                                      1,
                                      0,
                                      33.0 * scaleX,
                                      2652.0,
                                      0,
                                      1),
                                  alignment: Alignment.topLeft,
                                  child: SizedBox.expand(child: child),
                                )
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 1756.0,
                            right: 0.0,
                            bottom: null,
                            width: null,
                            height: 2.0,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width = constraints.maxWidth - 66.0;
                              final double scaleX =
                                  width <= 0 ? 0 : (width / 348.0);

                              final Widget child =
                                  GeneratedDividerLineWidget2();
                              return Stack(children: [
                                Transform(
                                  transform: Matrix4(
                                      scaleX,
                                      0,
                                      0,
                                      0,
                                      0,
                                      1,
                                      0,
                                      0,
                                      0,
                                      0,
                                      1,
                                      0,
                                      32.0 * scaleX,
                                      1756.0,
                                      0,
                                      1),
                                  alignment: Alignment.topLeft,
                                  child: SizedBox.expand(child: child),
                                )
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 3.0,
                            top: 896.0,
                            right: 3.0,
                            bottom: null,
                            width: null,
                            height: 807.0,
                            child: GeneratedAboutAboutWidget(),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.961352657004831;

                              final double height =
                                  constraints.maxHeight * 0.05133928571428571;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.021739130434782608,
                                    y: constraints.maxHeight * 3.0,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedPresidentsAddressWidget(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 9.0,
                            top: 3003.0,
                            right: null,
                            bottom: null,
                            width: 398.0,
                            height: 122.0,
                            child:
                                GeneratedMillenialsneedtobeempoweredtobedoersRishabhShahFounderP(),
                          ),
                          Positioned(
                            left: 107.0,
                            top: 2773.0,
                            right: null,
                            bottom: null,
                            width: 206.0,
                            height: 206.0,
                            child: GeneratedImage1Widget(),
                          ),
                          Positioned(
                            left: 90.0,
                            top: 3139.0,
                            right: null,
                            bottom: null,
                            width: 235.0,
                            height: 64.00011444091797,
                            child: GeneratedFrame13Widget(),
                          ),
                          Positioned(
                            left: 13.0,
                            top: 1792.0,
                            right: 9.0,
                            bottom: null,
                            width: null,
                            height: 739.0,
                            child: GeneratedWhatDoWeDoWidget(),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 45.0,
                            right: 0.0,
                            bottom: null,
                            width: null,
                            height: 60.0,
                            child: GeneratedHeaderWidget1(),
                          ),
                          Positioned(
                            left: 2.0,
                            top: 149.0,
                            right: null,
                            bottom: null,
                            width: 409.0,
                            height: 583.0,
                            child: GeneratedFrame2Widget(),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
