import 'package:flutter/material.dart';
import 'package:flutterapp/iimunapp/generatedknowmoredigitalwidget/generated/GeneratedInclusionsWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/iimunapp/generatedknowmoredigitalwidget/generated/GeneratedBasicDetailsWidget.dart';
import 'package:flutterapp/iimunapp/generatedknowmoredigitalwidget/generated/GeneratedBackWidget.dart';
import 'package:flutterapp/iimunapp/generatedknowmoredigitalwidget/generated/GeneratedUSDPayWidget.dart';
import 'package:flutterapp/iimunapp/generatedknowmoredigitalwidget/generated/GeneratedItenaryWidget.dart';
import 'package:flutterapp/iimunapp/generatedknowmoredigitalwidget/generated/GeneratedDescriptionWidget.dart';
import 'package:flutterapp/iimunapp/generatedknowmoredigitalwidget/generated/GeneratedImageConferenceWidget.dart';
import 'package:flutterapp/iimunapp/generatedknowmoredigitalwidget/generated/GeneratedDigitalConference580Widget.dart';
import 'package:flutterapp/iimunapp/generatedknowmoredigitalwidget/generated/GeneratedRectangle16Widget.dart';
import 'package:flutterapp/iimunapp/generatedknowmoredigitalwidget/generated/GeneratedCommAgendasWidget.dart';
import 'package:flutterapp/iimunapp/generatedknowmoredigitalwidget/generated/GeneratedHeaderWidget10.dart';
import 'package:flutterapp/iimunapp/generatedknowmoredigitalwidget/generated/GeneratedINRPay1Widget.dart';

/* Frame KnowMore - Digital
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedKnowMoreDigitalWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 3639.9617919921875,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 414.0,
                      height: 896.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width = constraints.maxWidth;

                                final double height =
                                    constraints.maxHeight * 0.3482144900730678;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: 0,
                                      y: constraints.maxHeight *
                                          1.1183033670697893,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedDescriptionWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width = constraints.maxWidth;

                                final double height =
                                    constraints.maxHeight * 1.3035714285714286;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: 0,
                                      y: constraints.maxHeight *
                                          2.4185267857142856,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedItenaryWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 1.0048309178743962;

                                final double height =
                                    constraints.maxHeight * 0.04348414284842355;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: 0,
                                      y: constraints.maxHeight *
                                          4.018973214285714,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedRectangle16Widget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 128.0,
                              top: 3492.0,
                              right: null,
                              bottom: null,
                              width: 157.99998474121094,
                              height: 49.999755859375,
                              child: GeneratedUSDPayWidget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.9999999262860432;

                                final double height =
                                    constraints.maxHeight * 0.20089272090366908;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: 0,
                                      y: constraints.maxHeight *
                                          1.6383928571428572,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedCommAgendasWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.9999999262860432;

                                final double height =
                                    constraints.maxHeight * 0.22544738224574498;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          -9.214244602958937e-9,
                                      y: constraints.maxHeight * 2.015625,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedInclusionsWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 1.0024155326511548;

                                final double height = constraints.maxHeight *
                                    0.060267857142857144;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: 0,
                                      y: constraints.maxHeight *
                                          0.6674107142857143,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedDigitalConference580Widget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width = constraints.maxWidth;

                                final double height =
                                    constraints.maxHeight * 0.41517857142857145;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: 0,
                                      y: constraints.maxHeight * 0.234375,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedImageConferenceWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width = constraints.maxWidth;

                                final double height =
                                    constraints.maxHeight * 0.2901787076677595;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: 0,
                                      y: constraints.maxHeight *
                                          0.8013392857142857,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedBasicDetailsWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width = constraints.maxWidth;

                                final double height =
                                    constraints.maxHeight * 0.06696428571428571;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          -2.1968471057317106e-15,
                                      y: constraints.maxHeight *
                                          0.12834821428571427,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedBackWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 2.2737367544323206e-13,
                              top: 45.0,
                              right: -2.2737367544323206e-13,
                              bottom: null,
                              width: null,
                              height: 60.0,
                              child: GeneratedHeaderWidget10(),
                            ),
                            Positioned(
                              left: 128.0,
                              top: 3395.0,
                              right: null,
                              bottom: null,
                              width: 158.0,
                              height: 55.20481872558594,
                              child: GeneratedINRPay1Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
