import 'package:flutter/material.dart';
import 'package:flutterapp/iimunapp/generatedconferencesdropdownwidget/generated/GeneratedYOUTHHUTWidget2.dart';
import 'package:flutterapp/iimunapp/generatedconferencesdropdownwidget/generated/GeneratedFAQWidget2.dart';
import 'package:flutterapp/iimunapp/generatedconferencesdropdownwidget/generated/GeneratedEXPERIENTIALLEARNINGWidget2.dart';
import 'package:flutterapp/iimunapp/generatedconferencesdropdownwidget/generated/GeneratedEXPERIENTIALLEARNINGWidget3.dart';
import 'package:flutterapp/iimunapp/generatedconferencesdropdownwidget/generated/GeneratedEXPERIENTIALLEARNINGWidget4.dart';
import 'package:flutterapp/iimunapp/generatedconferencesdropdownwidget/generated/GeneratedCONFERENCESWidget2.dart';

/* Frame Conferences-DropDown
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedConferencesDropDownWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 276.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 276.0,
                height: 70.0,
                child: GeneratedYOUTHHUTWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 70.0,
                right: null,
                bottom: null,
                width: 276.0,
                height: 70.0,
                child: GeneratedCONFERENCESWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 140.0,
                right: null,
                bottom: null,
                width: 276.0,
                height: 70.0,
                child: GeneratedEXPERIENTIALLEARNINGWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 210.0,
                right: null,
                bottom: null,
                width: 276.0,
                height: 70.0,
                child: GeneratedEXPERIENTIALLEARNINGWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 350.0,
                right: null,
                bottom: null,
                width: 276.0,
                height: 70.0,
                child: GeneratedFAQWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 280.0,
                right: null,
                bottom: null,
                width: 276.0,
                height: 70.0,
                child: GeneratedEXPERIENTIALLEARNINGWidget4(),
              )
            ]),
      ),
    ));
  }
}
