import 'package:flutter/material.dart';
import 'package:flutterapp/iimunapp/generatedeventsdropdownwidget/generated/GeneratedEXPERIENTIALLEARNINGWidget.dart';
import 'package:flutterapp/iimunapp/generatedeventsdropdownwidget/generated/GeneratedFAQWidget1.dart';
import 'package:flutterapp/iimunapp/generatedeventsdropdownwidget/generated/GeneratedCONFERENCESWidget.dart';
import 'package:flutterapp/iimunapp/generatedeventsdropdownwidget/generated/GeneratedYOUTHHUTWidget.dart';

/* Frame Events-DropDown
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEventsDropDownWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 276.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 276.0,
                height: 70.0,
                child: GeneratedYOUTHHUTWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 70.0,
                right: null,
                bottom: null,
                width: 276.0,
                height: 70.0,
                child: GeneratedCONFERENCESWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 140.0,
                right: null,
                bottom: null,
                width: 276.0,
                height: 70.0,
                child: GeneratedEXPERIENTIALLEARNINGWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 210.0,
                right: null,
                bottom: null,
                width: 276.0,
                height: 70.0,
                child: GeneratedFAQWidget1(),
              )
            ]),
      ),
    ));
  }
}
